version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.17
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  todo:
    build: .
    environment:
      - PORT=3000
  
  db:
    image: mysql:8.0.36-debian
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
#       - mysql-db:/var/lib/mysql



# volumes:
#   mysql-db: