version: '3'

services:
  nginx:
    ports:
      - 3000:80
  todo:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=secrettoken
      - REFRESH_TOKEN_SECRET=refreshsecrettokentoken
    
    command: npm run dev
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=789456123
      - MYSQL_DATABASE=tododb
      - MYSQL_USER=alireza
      - MYSQL_PASSWORD=12345
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080