CREATE TABLE IF NOT EXISTS tasks (
    uuid VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    creator_id VARCHAR(255) NOT NULL,
    todo_id VARCHAR(255) NOT NULL,
    status BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(uuid),
    FOREIGN KEY (todo_id) REFERENCES todos(uuid) ON DELETE CASCADE
)